from .from_file import (
    OSM,
    CloudTube,
    MikuInvidious,
    Neuters,
    SimplyTranslate,
    Twineo,
    Wikiless,
)
from .medium import LibMedium, Scribe
from .other import (
    AnonymousOverflow,
    BiblioReads,
    Binternet,
    BreezeWiki,
    Dumb,
    GotHub,
    Koub,
    Laboratory,
    Libremdb,
    Nitter,
    PrivateBin,
    Priviblur,
    Proxigram,
    ProxiTok,
    Quetre,
    Rimgo,
    RuralDictionary,
    SafeTwitch,
    Send,
    SkunkyArt,
    Suds,
    Tent,
    TransLite,
)
from .pixiv import PixivFE
from .reddit import Libreddit, Redlib, Teddit
from .search import LibreX, Searx, SearXNG, Whoogle
from .translate import LibreTranslate, LinvgaTranslate, Mozhi
from .wolfram import WolfreeAlpha
from .youtube import Hyperpipe, Invidious, Materialious, Piped, PipedMaterial, Poketube

INSTANCE_FETCHERS = (
    AnonymousOverflow,
    BiblioReads,
    Binternet,
    BreezeWiki,
    CloudTube,
    Dumb,
    GotHub,
    Hyperpipe,
    Invidious,
    Koub,
    Laboratory,
    LibMedium,
    LibreTranslate,
    LibreX,
    Libreddit,
    Libremdb,
    LinvgaTranslate,
    Materialious,
    MikuInvidious,
    Mozhi,
    Neuters,
    Nitter,
    OSM,
    Piped,
    PipedMaterial,
    PixivFE,
    Poketube,
    PrivateBin,
    Priviblur,
    ProxiTok,
    Proxigram,
    Quetre,
    Redlib,
    Rimgo,
    RuralDictionary,
    SafeTwitch,
    Scribe,
    SearXNG,
    Searx,
    Send,
    SimplyTranslate,
    SkunkyArt,
    Suds,
    Teddit,
    Tent,
    TransLite,
    Twineo,
    Whoogle,
    Wikiless,
    WolfreeAlpha,
)
