name: instances-updater

on:
  schedule:
    - cron: "10 22 * * *"
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: "Clone repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: "Install uv"
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.25"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: "Install the project"
        run: uv sync --no-dev

      - name: "Update frontends instances"
        run: uv run python main.py

      - name: "Commit changes"
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add -A
          git commit -m "Update instances" || :

      - name: "Push changes to GitHub"
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

      - name: "Mirror changes to Codeberg"
        shell: bash
        env:
          CODEBERG_TOKEN: ${{ secrets.CODEBERG_TOKEN }}
        run: |
          git config --unset-all http.https://github.com/.extraheader
          git push https://manerakai:$CODEBERG_TOKEN@codeberg.org/LibRedirect/instances
